// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
// import "./globals.css";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Smart Recipe Generator",
//   description: "Suggest recipes from your ingredients",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className="bg-neutral-900 text-neutral-100 min-h-dvh">
//         <div className="max-w-5xl mx-auto p-4">{children}</div>
//       </body>
//     </html>
//   );
// }
// app/layout.tsx
// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import ThemeToggle from '@/components/ThemeToggle'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Smart Recipe Generator',
//   description: 'Suggest recipes from your ingredients',
// }

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={`${inter.className} min-h-dvh bg-bg text-fg antialiased`}>
//         <header className="sticky top-0 z-50 bg-bg/80 backdrop-blur border-b border-[--color-border]">
//           <div className="mx-auto max-w-5xl px-4 py-3 flex items-center justify-between">
//             <div className="flex items-center gap-3">
//               <span className="text-lg font-semibold">🍳 Smart Recipe</span>
//               <span className="badge">beta</span>
//             </div>
//             <ThemeToggle />
//           </div>
//         </header>
//         <main className="mx-auto max-w-5xl p-4">{children}</main>
//       </body>
//     </html>
//   )
// }



// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import ThemeToggle from '@/components/ThemeToggle'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Smart Recipe Generator',
//   description: 'Suggest recipes from your ingredients',
// }

// // export const metadata: Metadata = {
// //   title: "Smart Recipe Generator",
// //   description: "Find delicious recipes from ingredients you already have.",
// //   openGraph: {
// //     title: "Smart Recipe Generator",
// //     description: "Find delicious recipes from ingredients you already have.",
// //     images: ["public/images/flatlay-with-food.jpg"],
// //     type: "website",
// //   },
// //   icons: { icon: "/favicon.ico" },
// // };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={`${inter.className} min-h-dvh bg-bg text-fg antialiased`}>
//         {/* Skip link for a11y */}
//         <a
//           href="#main"
//           className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-[60] px-3 py-2 rounded-lg bg-[--color-surface] border border-[--color-border] shadow"
//         >
//           Skip to content
//         </a>

//         {/* Glassy Navbar */}
//         <header className="sticky top-0 z-50 backdrop-blur-md bg-[color-mix(in_oklab,var(--color-surface)_80%,transparent)] border-b border-[--color-border]/80">
//           <div className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
//             {/* Brand */}
//             <div className="flex items-center gap-3">
//               <span className="text-2xl leading-none">🍳</span>
//               <span className="text-lg font-semibold tracking-tight">Smart Recipe</span>
//               <span className="px-2 py-0.5 text-xs rounded-full border border-[--color-border] text-[--color-muted]">
//                 beta
//               </span>
//             </div>

//             {/* Right actions */}
//             <div className="flex items-center gap-2">
//               <ThemeToggle />
//             </div>
//           </div>

//           {/* Subtle neon seam under header */}
//           <div className="h-px w-full bg-gradient-to-r from-[color-mix(in_oklab,var(--color-accent)_40%,transparent)]
//                          via-transparent to-[color-mix(in_oklab,var(--color-secondary)_35%,transparent)] opacity-70" />
//         </header>

//         {/* Page container */}
//         <main id="main" className="mx-auto max-w-6xl p-4">
//           {children}
//         </main>
//       </body>
//     </html>
//   )
// }

import "./globals.css"
import type { Metadata } from "next"
//import { Inter } from "next/font/google"
import ThemeToggle from "@/components/ThemeToggle"

// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap", // ensures fallback swap behavior
// })

export const metadata: Metadata = {
  title: "Smart Recipe Generator",
  description: "Suggest recipes from your ingredients",
  // You can uncomment this for full SEO later
  // openGraph: {
  //   title: "Smart Recipe Generator",
  //   description: "Find delicious recipes from ingredients you already have.",
  //   images: ["/images/flatlay-with-food.jpg"], // no "public/" prefix
  //   type: "website",
  // },
  // icons: { icon: "/favicon.ico" },
}

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" suppressHydrationWarning className={inter.className}>
//       <body className="min-h-dvh bg-bg text-fg antialiased">
//         {/* Skip link for a11y */}
//         <a
//           href="#main"
//           className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-[60] px-3 py-2 rounded-lg bg-[--color-surface] border border-[--color-border] shadow"
//         >
//           Skip to content
//         </a>

//         {/* Glassy Navbar */}
//         <header className="sticky top-0 z-50 backdrop-blur-md bg-[color-mix(in_oklab,var(--color-surface)_80%,transparent)] border-b border-[--color-border]/80">
//           <div className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
//             {/* Brand */}
//             <div className="flex items-center gap-3">
//               <span className="text-2xl leading-none">🍳</span>
//               <span className="text-lg font-semibold tracking-tight">Smart Recipe</span>
//               <span className="px-2 py-0.5 text-xs rounded-full border border-[--color-border] text-[--color-muted]">
//                 beta
//               </span>
//             </div>

//             {/* Right actions */}
//             <div className="flex items-center gap-2">
//               <ThemeToggle />
//             </div>
//           </div>

//           {/* Subtle neon seam under header */}
//           <div className="h-px w-full bg-gradient-to-r from-[color-mix(in_oklab,var(--color-accent)_40%,transparent)]
//                          via-transparent to-[color-mix(in_oklab,var(--color-secondary)_35%,transparent)] opacity-70" />
//         </header>

//         {/* Page container */}
//         <main id="main" className="mx-auto max-w-6xl p-4">
//           {children}
//         </main>
//       </body>
//     </html>
//   )
// }


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-dvh bg-bg text-fg antialiased font-sans">
        {/* Skip link for a11y */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-[60] px-3 py-2 rounded-lg bg-[--color-surface] border border-[--color-border] shadow"
        >
          Skip to content
        </a>

        {/* Glassy Navbar */}
        <header className="sticky top-0 z-50 backdrop-blur-md bg-[color-mix(in_oklab,var(--color-surface)_80%,transparent)] border-b border-[--color-border]/80">
          <div className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
            {/* Brand */}
            <div className="flex items-center gap-3">
              <span className="text-2xl leading-none">🍳</span>
              <span className="text-lg font-semibold tracking-tight">Smart Recipe</span>
              <span className="px-2 py-0.5 text-xs rounded-full border border-[--color-border] text-[--color-muted]">
                beta
              </span>
            </div>

            {/* Right actions */}
            <div className="flex items-center gap-2">
              <ThemeToggle />
            </div>
          </div>

          {/* Subtle neon seam under header */}
          <div className="h-px w-full bg-gradient-to-r from-[color-mix(in_oklab,var(--color-accent)_40%,transparent)]
                         via-transparent to-[color-mix(in_oklab,var(--color-secondary)_35%,transparent)] opacity-70" />
        </header>

        {/* Page container */}
        <main id="main" className="mx-auto max-w-6xl p-4">
          {children}
        </main>
      </body>
    </html>
  )
}