import type { Recipe } from './types'

// Sample Indian recipes data

export const RECIPES: Recipe[] =  [
  {
    id: 'chana-masala',
    title: 'Chana Masala',
    cuisine: 'Indian',
   
    ingredients: [
      { name: 'chickpeas', quantity: '2 cups cooked' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato', quantity: '2 medium, chopped' },
      { name: 'ginger garlic paste', quantity: '1 tbsp' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'cumin', quantity: '1 tsp' },
      { name: 'turmeric', quantity: '1/2 tsp' },
    ],
    steps: [
      'Sauté onion, add ginger-garlic and spices.',
      'Add tomatoes and cook down.',
      'Add chickpeas and simmer 10 min.',
    ],
    timeMinutes: 35,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan', 'gluten-free'],
    servings: 3,
   image: "/images/chanamasala.jpeg",
    nutritionPerServing: { calories: 280, protein: 12, carbs: 42, fat: 6 },
  },
  {
    id: 'palak-paneer',
    title: 'Palak Paneer',
    cuisine: 'Indian',
 
   
    ingredients: [
      { name: 'spinach', quantity: '250g' },
      { name: 'paneer', quantity: '200g' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato', quantity: '1 medium, chopped' },
      { name: 'ginger garlic paste', quantity: '1 tsp' },
      { name: 'cumin', quantity: '1 tsp' },
      { name: 'cream', quantity: '2 tbsp' },
    ],
    steps: [
      'Blanch and puree spinach.',
      'Sauté onion, tomato, and spices.',
      'Add spinach puree and paneer cubes.',
      'Finish with cream.',
    ],
    timeMinutes: 30,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
     image: "/images/palakpanner.jpeg",

    
    nutritionPerServing: { calories: 320, protein: 15, carbs: 20, fat: 18 },
  },
  {
    id: 'butter-chicken',
    title: 'Butter Chicken',
    cuisine: 'Indian',
    ingredients: [
      { name: 'chicken', quantity: '500g' },
      { name: 'butter', quantity: '3 tbsp' },
      { name: 'onion', quantity: '1 large, chopped' },
      { name: 'tomato puree', quantity: '1 cup' },
      { name: 'cream', quantity: '1/2 cup' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'ginger garlic paste', quantity: '1 tbsp' },
    ],
    steps: [
      'Marinate chicken in spices and cook.',
      'Prepare tomato-onion gravy with butter.',
      'Add chicken, simmer, and finish with cream.',
    ],
    timeMinutes: 45,
    difficulty: 'medium',
    dietTags: ['non-veg', 'gluten-free'],
    servings: 4,
  image: "/images/AdobeStock_1335218382_Preview.jpeg",

    
   
    nutritionPerServing: { calories: 420, protein: 28, carbs: 12, fat: 30 },
  },
  {
    id: 'veg-biryani',
    title: 'Vegetable Biryani',
    cuisine: 'Indian',
    ingredients: [
      { name: 'basmati rice', quantity: '2 cups' },
      { name: 'mixed vegetables', quantity: '2 cups' },
      { name: 'onion', quantity: '2 large, sliced' },
      { name: 'tomato', quantity: '1 large' },
      { name: 'ginger garlic paste', quantity: '1 tbsp' },
      { name: 'biryani masala', quantity: '2 tsp' },
      { name: 'ghee', quantity: '2 tbsp' },
    ],
    steps: [
      'Cook rice until 70% done.',
      'Prepare vegetable masala with spices.',
      'Layer rice and masala, cook on dum.',
    ],
    timeMinutes: 50,
    difficulty: 'medium',
    dietTags: ['veg'],
    servings: 4,
    image: '/images/vegbriyani.jpeg',
    
    
    nutritionPerServing: { calories: 350, protein: 9, carbs: 60, fat: 10 },
  },
  {
    id: 'dal-tadka',
    title: 'Dal Tadka',
    cuisine: 'Indian',
    ingredients: [
      { name: 'toor dal', quantity: '1 cup' },
      { name: 'onion', quantity: '1 medium' },
      { name: 'tomato', quantity: '1 medium' },
      { name: 'garlic', quantity: '3 cloves' },
      { name: 'turmeric', quantity: '1/2 tsp' },
      { name: 'ghee', quantity: '2 tbsp' },
      { name: 'cumin', quantity: '1 tsp' },
    ],
    steps: [
      'Cook dal with turmeric until soft.',
      'Prepare tadka with ghee, cumin, garlic, onion, tomato.',
      'Mix tadka into dal and simmer 5 minutes.',
    ],
    timeMinutes: 30,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
  image: "/images/dal-tadka.jpeg",


    
    
    nutritionPerServing: { calories: 240, protein: 11, carbs: 35, fat: 7 },
  },
  {
    id: 'masala-dosa',
    title: 'Masala Dosa',
    cuisine: 'South Indian',
    ingredients: [
      { name: 'dosa batter', quantity: '2 cups' },
      { name: 'potato', quantity: '3 medium, boiled' },
      { name: 'onion', quantity: '1 large, sliced' },
      { name: 'green chilli', quantity: '2' },
      { name: 'curry leaves', quantity: '6' },
      { name: 'mustard seeds', quantity: '1 tsp' },
      { name: 'turmeric', quantity: '1/2 tsp' },
    ],
    steps: [
      'Prepare potato masala filling.',
      'Spread dosa batter on hot tawa.',
      'Place filling inside and fold.',
    ],
    timeMinutes: 40,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 4,
    image: '/images/masala dosa.jpeg',
    
    nutritionPerServing: { calories: 300, protein: 7, carbs: 50, fat: 8 },
  },
  {
    id: 'idli-sambar',
    title: 'Idli with Sambar',
    cuisine: 'South Indian',
    ingredients: [
      { name: 'idli batter', quantity: '2 cups' },
      { name: 'toor dal', quantity: '1/2 cup' },
      { name: 'tamarind', quantity: '2 tbsp' },
      { name: 'onion', quantity: '1 medium' },
      { name: 'tomato', quantity: '1 medium' },
      { name: 'sambar powder', quantity: '2 tsp' },
      { name: 'curry leaves', quantity: '6' },
    ],
    steps: [
      'Steam idlis from batter.',
      'Prepare sambar with dal, tamarind, and spices.',
      'Serve hot idlis with sambar.',
    ],
    timeMinutes: 45,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 4,
    image: '/images/idli sambhar.jpeg',
    
    nutritionPerServing: { calories: 280, protein: 9, carbs: 52, fat: 4 },
  },
  {
    id: 'pav-bhaji',
    title: 'Pav Bhaji',
    cuisine: 'Indian Street Food',
    ingredients: [
      { name: 'pav bread', quantity: '8 pieces' },
      { name: 'potato', quantity: '2 large, boiled' },
      { name: 'peas', quantity: '1/2 cup' },
      { name: 'onion', quantity: '1 large, chopped' },
      { name: 'tomato', quantity: '2 large, chopped' },
      { name: 'pav bhaji masala', quantity: '2 tsp' },
      { name: 'butter', quantity: '3 tbsp' },
    ],
    steps: [
      'Mash boiled vegetables.',
      'Cook with onion, tomato, and masala.',
      'Toast pav in butter and serve with bhaji.',
    ],
    timeMinutes: 35,
    difficulty: 'easy',
    dietTags: ['veg'],
    servings: 4,
    image: '/images/pavbahji.jpeg',
    
    nutritionPerServing: { calories: 320, protein: 8, carbs: 55, fat: 10 },
  },
  {
    id: 'rajma-curry',
    title: 'Rajma Curry',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'rajma', quantity: '1 cup soaked and cooked' },
      { name: 'onion', quantity: '1 large, chopped' },
      { name: 'tomato', quantity: '2 medium, pureed' },
      { name: 'ginger garlic paste', quantity: '1 tbsp' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'turmeric', quantity: '1/2 tsp' },
    ],
    steps: [
      'Cook onion, tomato, and spices into gravy.',
      'Add cooked rajma and simmer 20 min.',
    ],
    timeMinutes: 40,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 4,
    image: '/images/rajma curry.jpeg',
    
    nutritionPerServing: { calories: 310, protein: 13, carbs: 52, fat: 5 },
  },

  { id: 'chole-bhature',
    title: 'Chole Bhature',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'chickpeas', quantity: '1 cup soaked' },
      { name: 'onion', quantity: '1 large, chopped' },
      { name: 'tomato', quantity: '2 medium, pureed' },
      { name: 'ginger garlic paste', quantity: '1 tbsp' },
      { name: 'chole masala', quantity: '2 tsp' },
      { name: 'flour', quantity: '2 cups' },
      { name: 'oil', quantity: 'for frying' },
    ],
    steps: [
      'Cook chickpeas with spices to make chole.',
      'Prepare dough for bhature and deep fry.',
      'Serve hot bhature with chole.',
    ],
    timeMinutes: 60,
    difficulty: 'medium',
    dietTags: ['veg'],
    servings: 4,
    image: '/images/chole bhature.jpeg',
    
    nutritionPerServing: { calories: 450, protein: 12, carbs: 65, fat: 15 },
  },
  {
    id: 'aloo-gobi',
    title: 'Aloo Gobi',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'potato', quantity: '2 medium, cubed' },
      { name: 'cauliflower', quantity: '1 medium, florets' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato', quantity: '1 medium, chopped' },
      { name: 'turmeric', quantity: '1 tsp' },
      { name: 'cumin', quantity: '1 tsp' },
      { name: 'garam masala', quantity: '1 tsp' },
    ],
    steps: [
      'Sauté onions and spices.',
      'Add potato and cauliflower, cook covered.',
      'Add tomato and simmer until vegetables are tender.',
    ],
    timeMinutes: 30,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 3,
    image: '/images/aloogobhi.jpeg',
    nutritionPerServing: { calories: 200, protein: 5, carbs: 30, fat: 6 },
  },
  {
    id: 'matar-paneer',
    title: 'Matar Paneer',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'paneer', quantity: '200g, cubed' },
      { name: 'green peas', quantity: '1 cup' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato', quantity: '1 medium, pureed' },
      { name: 'ginger garlic paste', quantity: '1 tsp' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'cream', quantity: '2 tbsp' },
    ],
    steps: [
      'Sauté onion, tomato, and spices.',
      'Add peas and paneer cubes.',
      'Simmer and finish with cream.',
    ],
    timeMinutes: 30,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
    image: '/images/matarpaneer.jpeg',
    
    nutritionPerServing: { calories: 320, protein: 15, carbs: 18, fat: 20 },
  },
  {
    id: 'tandoori-chicken',
    title: 'Tandoori Chicken',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'chicken', quantity: '500g' },
      { name: 'yogurt', quantity: '1/2 cup' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'red chili powder', quantity: '1 tsp' },
      { name: 'ginger garlic paste', quantity: '1 tbsp' },
      { name: 'lemon juice', quantity: '1 tbsp' },
      { name: 'oil', quantity: '2 tbsp' },
    ],
    steps: [
      'Marinate chicken with yogurt and spices.',
      'Grill or bake until cooked.',
      'Serve hot with lemon wedges.',
    ],
    timeMinutes: 50,
    difficulty: 'medium',
    dietTags: ['non-veg', 'gluten-free'],
    servings: 4,
    image: '/images/tandoorichicken.jpeg',
    
    nutritionPerServing: { calories: 280, protein: 30, carbs: 2, fat: 18 },
  },
  {
    id: 'dal-makhani',
    title: 'Dal Makhani',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'whole urad dal', quantity: '1 cup' },
      { name: 'kidney beans', quantity: '1/4 cup' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato', quantity: '2 medium, pureed' },
      { name: 'ginger garlic paste', quantity: '1 tbsp' },
      { name: 'butter', quantity: '2 tbsp' },
      { name: 'cream', quantity: '2 tbsp' },
    ],
    steps: [
      'Cook dal and kidney beans until soft.',
      'Prepare gravy with butter, onion, tomato, and spices.',
      'Add cooked dal, simmer, and finish with cream.',
    ],
    timeMinutes: 90,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 4,
    image: '/images/dal.jpeg',
    
    nutritionPerServing: { calories: 350, protein: 15, carbs: 45, fat: 12 },
  },
  {
    id: 'kadhi-pakora',
    title: 'Kadhi Pakora',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'gram flour', quantity: '1 cup' },
      { name: 'yogurt', quantity: '2 cups' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'turmeric', quantity: '1/2 tsp' },
      { name: 'cumin seeds', quantity: '1 tsp' },
      { name: 'mustard seeds', quantity: '1 tsp' },
      { name: 'oil', quantity: '2 tbsp' },
    ],
    steps: [
      'Prepare pakoras from gram flour and fry.',
      'Make yogurt-turmeric kadhi.',
      'Add pakoras to kadhi and simmer 10 minutes.',
    ],
    timeMinutes: 45,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 4,
    image: '/images/kadhipakora.jpeg',
    
    nutritionPerServing: { calories: 220, protein: 8, carbs: 30, fat: 8 },
  },

  {id: 'paneer-butter-masala',
    title: 'Paneer Butter Masala',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'paneer', quantity: '200g, cubed' },
      { name: 'butter', quantity: '2 tbsp' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato puree', quantity: '1 cup' },
      { name: 'cream', quantity: '2 tbsp' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'ginger garlic paste', quantity: '1 tsp' },
    ],
    steps: [
      'Sauté onion, ginger garlic paste, and tomato puree.',
      'Add butter and paneer cubes.',
      'Simmer and finish with cream and garam masala.',
    ],
    timeMinutes: 30,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
    image: '/images/paneerbuttermasala.jpeg',
    
    nutritionPerServing: { calories: 330, protein: 14, carbs: 18, fat: 22 },
  },

  {
    id: 'gobi-manchurian',
    title: 'Gobi Manchurian',
    cuisine: 'Indo-Chinese',
    ingredients: [
      { name: 'cauliflower', quantity: '1 medium, florets' },
      { name: 'cornflour', quantity: '3 tbsp' },
      { name: 'all-purpose flour', quantity: '2 tbsp' },
      { name: 'soy sauce', quantity: '2 tsp' },
      { name: 'ginger garlic paste', quantity: '1 tsp' },
      { name: 'green chili', quantity: '2, chopped' },
      { name: 'oil', quantity: 'for frying' },
    ],
    steps: [
      'Coat cauliflower in flour and deep fry.',
      'Prepare sauce with soy, ginger-garlic, and chili.',
      'Toss fried cauliflower in sauce and serve.',
    ],
    timeMinutes: 35,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 4,
    image: '/images/gobhi manchurian.jpeg',
    
    nutritionPerServing: { calories: 250, protein: 5, carbs: 25, fat: 15 },
  },
  {
    id: 'bhindi-masala',
    title: 'Bhindi Masala',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'okra', quantity: '250g, chopped' },
      { name: 'onion', quantity: '1 medium, sliced' },
      { name: 'tomato', quantity: '1 medium, chopped' },
      { name: 'cumin seeds', quantity: '1 tsp' },
      { name: 'turmeric', quantity: '1/2 tsp' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'oil', quantity: '2 tbsp' },
    ],
    steps: [
      'Sauté onions with spices.',
      'Add okra and cook until tender.',
      'Add tomatoes and simmer 5 minutes.',
    ],
    timeMinutes: 25,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 3,
    image: '/images/bhindimasala.jpeg',
    
    nutritionPerServing: { calories: 120, protein: 3, carbs: 15, fat: 6 },
  },
  {
    id: 'rajma-chawal',
    title: 'Rajma Chawal',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'kidney beans', quantity: '1 cup soaked' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato', quantity: '2 medium, pureed' },
      { name: 'ginger garlic paste', quantity: '1 tsp' },
      { name: 'rice', quantity: '1 cup' },
      { name: 'cumin', quantity: '1 tsp' },
      { name: 'oil', quantity: '2 tbsp' },
    ],
    steps: [
      'Cook kidney beans with spices to make rajma.',
      'Cook rice separately.',
      'Serve rajma over steamed rice.',
    ],
    timeMinutes: 50,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 4,
    image: '/images/rajmachawal.jpeg',
    
    nutritionPerServing: { calories: 400, protein: 15, carbs: 70, fat: 8 },
  },
  {
    id: 'vada-pav',
    title: 'Vada Pav',
    cuisine: 'Maharashtrian',
    ingredients: [
      { name: 'potato', quantity: '2 medium, boiled and mashed' },
      { name: 'bread buns', quantity: '4' },
      { name: 'gram flour', quantity: '1/2 cup' },
      { name: 'green chili', quantity: '1, chopped' },
      { name: 'ginger garlic paste', quantity: '1 tsp' },
      { name: 'oil', quantity: 'for frying' },
      { name: 'mustard seeds', quantity: '1/2 tsp' },
    ],
    steps: [
      'Prepare spiced potato filling.',
      'Coat with gram flour batter and deep fry.',
      'Serve inside bread buns with chutney.',
    ],
    timeMinutes: 30,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 4,
    image: '/images/vadapav.jpeg',
    
    nutritionPerServing: { calories: 300, protein: 6, carbs: 40, fat: 12 },
  },
  {
    id: 'poha',
    title: 'Poha',
    cuisine: 'Maharashtrian',
    ingredients: [
      { name: 'flattened rice', quantity: '1 cup' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'green chili', quantity: '1, chopped' },
      { name: 'mustard seeds', quantity: '1 tsp' },
      { name: 'curry leaves', quantity: '8-10' },
      { name: 'peanuts', quantity: '2 tbsp' },
      { name: 'oil', quantity: '2 tbsp' },
    ],
    steps: [
      'Rinse and soak flattened rice.',
      'Sauté onions, chili, curry leaves, and peanuts.',
      'Add rice and season, cook until done.',
    ],
    timeMinutes: 20,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 2,
    image: '/images/poha.jpeg',
    
    nutritionPerServing: { calories: 180, protein: 5, carbs: 35, fat: 6 },
  },
  {
    id: 'pani-puri',
    title: 'Pani Puri',
    cuisine: 'Indian Street Food',
    ingredients: [
      { name: 'puri', quantity: '20 pieces' },
      { name: 'boiled potato', quantity: '2 medium' },
      { name: 'boiled chickpeas', quantity: '1/2 cup' },
      { name: 'tamarind paste', quantity: '2 tbsp' },
      { name: 'mint', quantity: '1/2 cup' },
      { name: 'green chili', quantity: '1' },
      { name: 'water', quantity: '2 cups' },
    ],
    steps: [
      'Prepare spicy tangy water with tamarind and mint.',
      'Mix potato and chickpeas for filling.',
      'Fill puris with mixture and serve with water.',
    ],
    timeMinutes: 25,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 4,
    image: '/images/pani puri.jpeg',
    
    nutritionPerServing: { calories: 120, protein: 3, carbs: 20, fat: 2 },
  },
  {
    id: 'dhokla',
    title: 'Dhokla',
    cuisine: 'Gujarati',
    ingredients: [
      { name: 'gram flour', quantity: '1 cup' },
      { name: 'yogurt', quantity: '1/2 cup' },
      { name: 'turmeric', quantity: '1/4 tsp' },
      { name: 'green chili', quantity: '1' },
      { name: 'mustard seeds', quantity: '1 tsp' },
      { name: 'oil', quantity: '1 tbsp' },
      { name: 'baking soda', quantity: '1/2 tsp' },
    ],
    steps: [
      'Mix gram flour, yogurt, turmeric, and baking soda into batter.',
      'Steam the batter until fluffy.',
      'Prepare tempering with mustard seeds and pour over dhokla.',
    ],
    timeMinutes: 35,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 4,
    image: '/images/dhokhla.jpeg',
    
    nutritionPerServing: { calories: 150, protein: 6, carbs: 25, fat: 4 },
  },
  {
    id: 'thepla',
    title: 'Thepla',
    cuisine: 'Gujarati',
    ingredients: [
      { name: 'wheat flour', quantity: '2 cups' },
      { name: 'fenugreek leaves', quantity: '1/2 cup, chopped' },
      { name: 'turmeric', quantity: '1/2 tsp' },
      { name: 'red chili powder', quantity: '1/2 tsp' },
      { name: 'oil', quantity: '2 tbsp' },
      { name: 'water', quantity: 'as needed' },
    ],
    steps: [
      'Mix flour, fenugreek leaves, and spices into dough.',
      'Roll into thin flatbreads and cook on tawa with oil.',
    ],
    timeMinutes: 25,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan'],
    servings: 4,
    image: '/images/thepla.jpeg',
    
    nutritionPerServing: { calories: 180, protein: 5, carbs: 30, fat: 5 },
  },
  {
    id: 'undhiyu',
    title: 'Undhiyu',
    cuisine: 'Gujarati',
    ingredients: [
      { name: 'mixed vegetables', quantity: '3 cups' },
      { name: 'fenugreek leaves', quantity: '1/2 cup' },
      { name: 'coriander powder', quantity: '1 tsp' },
      { name: 'ginger garlic paste', quantity: '1 tsp' },
      { name: 'oil', quantity: '3 tbsp' },
      { name: 'coconut', quantity: '1/4 cup grated' },
      { name: 'spices', quantity: 'as needed' },
    ],
    steps: [
      'Mix vegetables with spices and fenugreek leaves.',
      'Cook on low heat until tender.',
      'Serve hot with flatbread.',
    ],
    timeMinutes: 60,
    difficulty: 'hard',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 4,
    image: '/images/undhiyu.jpeg',
    
    nutritionPerServing: { calories: 250, protein: 6, carbs: 35, fat: 10 },
  },
  {
    id: 'fish-curry',
    title: 'Bengali Fish Curry',
    cuisine: 'Bengali',
    ingredients: [
      { name: 'fish', quantity: '500g' },
      { name: 'mustard seeds', quantity: '1 tsp' },
      { name: 'turmeric', quantity: '1 tsp' },
      { name: 'mustard oil', quantity: '2 tbsp' },
      { name: 'green chili', quantity: '2' },
      { name: 'tomato', quantity: '1 medium, chopped' },
    ],
    steps: [
      'Marinate fish with turmeric and salt.',
      'Prepare mustard-tomato sauce.',
      'Cook fish in sauce until done.',
    ],
    timeMinutes: 35,
    difficulty: 'medium',
    dietTags: ['non-veg', 'gluten-free'],
    servings: 4,
    image: '/images/fish curry.jpeg',
    
    nutritionPerServing: { calories: 250, protein: 28, carbs: 5, fat: 12 },
  },
  {
    id: 'misal-pav',
    title: 'Misal Pav',
    cuisine: 'Maharashtrian',
    ingredients: [
      { name: 'sprouted beans', quantity: '1 cup' },
      { name: 'onion', quantity: '1 medium' },
      { name: 'tomato', quantity: '1 medium' },
      { name: 'misal masala', quantity: '1 tbsp' },
      { name: 'oil', quantity: '2 tbsp' },
      { name: 'bread rolls', quantity: '4' },
    ],
    steps: [
      'Cook sprouted beans with misal masala.',
      'Prepare spicy gravy.',
      'Serve with bread rolls and garnish with onion and lemon.',
    ],
    timeMinutes: 40,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 4,
    image: '/images/misalpav.jpeg',
    
    nutritionPerServing: { calories: 280, protein: 12, carbs: 40, fat: 10 },
  },
  {
    id: 'prawn-curry',
    title: 'Goan Prawn Curry',
    cuisine: 'Goan',
    ingredients: [
      { name: 'prawns', quantity: '500g' },
      { name: 'coconut milk', quantity: '1 cup' },
      { name: 'red chili powder', quantity: '1 tsp' },
      { name: 'turmeric', quantity: '1/2 tsp' },
      { name: 'mustard seeds', quantity: '1 tsp' },
      { name: 'oil', quantity: '2 tbsp' },
    ],
    steps: [
      'Marinate prawns with spices.',
      'Cook in coconut milk with mustard seeds and oil.',
      'Simmer until prawns are cooked.',
    ],
    timeMinutes: 35,
    difficulty: 'medium',
    dietTags: ['non-veg', 'gluten-free'],
    servings: 4,
    image: '/images/prawncurry.jpeg',
    
    nutritionPerServing: { calories: 300, protein: 32, carbs: 6, fat: 15 },
  },
  {
    id: 'methi-paratha',
    title: 'Methi Paratha',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'wheat flour', quantity: '2 cups' },
      { name: 'fenugreek leaves', quantity: '1/2 cup, chopped' },
      { name: 'oil', quantity: '2 tbsp' },
      { name: 'salt', quantity: 'to taste' },
    ],
    steps: [
      'Mix flour, methi leaves, and salt into dough.',
      'Roll into flatbreads and cook on tawa with oil.',
    ],
    timeMinutes: 20,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan'],
    servings: 4,
    image: '/images/methiparatha.jpeg',
    
    nutritionPerServing: { calories: 180, protein: 5, carbs: 30, fat: 5 },
  },
  {
    id: 'chicken-korma',
    title: 'Chicken Korma',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'chicken', quantity: '500g' },
      { name: 'yogurt', quantity: '1/2 cup' },
      { name: 'onion', quantity: '1 large, chopped' },
      { name: 'cream', quantity: '1/4 cup' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'ginger garlic paste', quantity: '1 tbsp' },
      { name: 'oil', quantity: '2 tbsp' },
    ],
    steps: [
      'Marinate chicken with yogurt and spices.',
      'Cook onions, add chicken and simmer.',
      'Finish with cream and garam masala.',
    ],
    timeMinutes: 50,
    difficulty: 'medium',
    dietTags: ['non-veg', 'gluten-free'],
    servings: 4,
    image: '/images/chickenkorma.jpeg',
    
    nutritionPerServing: { calories: 380, protein: 32, carbs: 8, fat: 25 },
  },
  {
    id: 'kadai-paneer',
    title: 'Kadai Paneer',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'paneer', quantity: '200g, cubed' },
      { name: 'capsicum', quantity: '1 medium, chopped' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato puree', quantity: '1 cup' },
      { name: 'kadai masala', quantity: '2 tsp' },
      { name: 'oil', quantity: '2 tbsp' },
      { name: 'ginger garlic paste', quantity: '1 tsp' },
    ],
    steps: [
      'Sauté onions, capsicum, and ginger garlic paste.',
      'Add tomato puree and kadai masala.',
      'Add paneer cubes and simmer 10 minutes.',
    ],
    timeMinutes: 35,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
    image: '/images/khadipaneer.jpeg',
    
    nutritionPerServing: { calories: 320, protein: 15, carbs: 20, fat: 18 },
  },


  {id: 'veg-korma',
    title: 'Vegetable Korma',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'mixed vegetables', quantity: '2 cups' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato', quantity: '1 medium, pureed' },
      { name: 'cream', quantity: '3 tbsp' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'cashew paste', quantity: '2 tbsp' },
      { name: 'oil', quantity: '2 tbsp' },
    ],
    steps: [
      'Sauté onions and tomato puree.',
      'Add vegetables and cook partially.',
      'Add cashew paste, cream, and garam masala. Simmer 10 min.',
    ],
    timeMinutes: 35,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
    image: '/images/vegkorma.jpeg',
    
    nutritionPerServing: { calories: 280, protein: 8, carbs: 25, fat: 15 },
  },
  {
    id: 'aloo-methi',
    title: 'Aloo Methi',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'potato', quantity: '2 medium, cubed' },
      { name: 'fenugreek leaves', quantity: '1 cup, chopped' },
      { name: 'turmeric', quantity: '1/2 tsp' },
      { name: 'cumin seeds', quantity: '1 tsp' },
      { name: 'oil', quantity: '2 tbsp' },
      { name: 'green chili', quantity: '1, chopped' },
    ],
    steps: [
      'Heat oil, add cumin seeds and turmeric.',
      'Add potatoes and cook until half done.',
      'Add methi leaves, simmer until potatoes are tender.',
    ],
    timeMinutes: 25,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 3,
    image: '/images/aloo methi.jpeg',
    
    nutritionPerServing: { calories: 180, protein: 4, carbs: 30, fat: 6 },
  },
  {
    id: 'pulao',
    title: 'Vegetable Pulao',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'basmati rice', quantity: '1.5 cups' },
      { name: 'mixed vegetables', quantity: '1.5 cups' },
      { name: 'onion', quantity: '1 medium, sliced' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'ghee', quantity: '2 tbsp' },
      { name: 'cumin seeds', quantity: '1 tsp' },
    ],
    steps: [
      'Sauté onions, cumin seeds, and vegetables in ghee.',
      'Add rice, water, and garam masala.',
      'Cook until rice is tender and fluffy.',
    ],
    timeMinutes: 30,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free'],
    servings: 4,
    image: '/images/pulao.jpeg',
    
    nutritionPerServing: { calories: 250, protein: 6, carbs: 45, fat: 8 },
  },
  {
    id: 'egg-bhurji',
    title: 'Egg Bhurji',
    cuisine: 'Indian',
    ingredients: [
      { name: 'eggs', quantity: '4' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato', quantity: '1 medium, chopped' },
      { name: 'green chili', quantity: '1' },
      { name: 'turmeric', quantity: '1/4 tsp' },
      { name: 'oil', quantity: '2 tbsp' },
    ],
    steps: [
      'Sauté onion, chili, and tomato in oil.',
      'Add beaten eggs and turmeric, scramble until cooked.',
    ],
    timeMinutes: 15,
    difficulty: 'easy',
    dietTags: ['non-veg', 'gluten-free'],
    servings: 2,
    image: '/images/egg curry.jpeg',
    
    nutritionPerServing: { calories: 180, protein: 12, carbs: 6, fat: 12 },
  },
  {
    id: 'mango-lassi',
    title: 'Mango Lassi',
    cuisine: 'Indian',
    ingredients: [
      { name: 'mango', quantity: '1 cup, chopped' },
      { name: 'yogurt', quantity: '1 cup' },
      { name: 'sugar', quantity: '2 tbsp' },
      { name: 'cardamom powder', quantity: '1/4 tsp' },
      { name: 'ice cubes', quantity: '4-5' },
    ],
    steps: [
      'Blend mango, yogurt, sugar, and cardamom until smooth.',
      'Serve chilled with ice cubes.',
    ],
    timeMinutes: 5,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free'],
    servings: 2,
    image: '/images/mangolassi.jpeg',
    
    nutritionPerServing: { calories: 150, protein: 4, carbs: 30, fat: 2 },
  },
  {
    id: 'methi-thepla',
    title: 'Methi Thepla',
    cuisine: 'Gujarati',
    ingredients: [
      { name: 'wheat flour', quantity: '2 cups' },
      { name: 'fenugreek leaves', quantity: '1/2 cup' },
      { name: 'turmeric', quantity: '1/2 tsp' },
      { name: 'red chili powder', quantity: '1/2 tsp' },
      { name: 'oil', quantity: '2 tbsp' },
      { name: 'water', quantity: 'as needed' },
    ],
    steps: [
      'Mix flour, methi, turmeric, chili, and water into dough.',
      'Roll into flatbreads and cook on tawa with oil.',
    ],
    timeMinutes: 25,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan'],
    servings: 4,
    image: '/images/mthithepla.jpeg',
    
    nutritionPerServing: { calories: 180, protein: 5, carbs: 30, fat: 5 },
  },
  {
    id: 'paneer-tikka',
    title: 'Paneer Tikka',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'paneer', quantity: '200g, cubes' },
      { name: 'yogurt', quantity: '1/4 cup' },
      { name: 'red chili powder', quantity: '1 tsp' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'lemon juice', quantity: '1 tbsp' },
      { name: 'oil', quantity: '1 tbsp' },
    ],
    steps: [
      'Marinate paneer in yogurt and spices.',
      'Grill or bake until lightly charred.',
      'Serve hot with chutney.',
    ],
    timeMinutes: 25,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
    image: '/images/paneertikka.jpeg',
    nutritionPerServing: { calories: 200, protein: 14, carbs: 6, fat: 12 },
  },
  {
    id: 'masala-papad',
    title: 'Masala Papad',
    cuisine: 'Indian Snack',
    ingredients: [
      { name: 'papad', quantity: '4' },
      { name: 'onion', quantity: '1 small, finely chopped' },
      { name: 'tomato', quantity: '1 small, chopped' },
      { name: 'coriander', quantity: '2 tbsp, chopped' },
      { name: 'chili powder', quantity: '1/4 tsp' },
      { name: 'lemon juice', quantity: '1 tsp' },
    ],
    steps: [
      'Roast papads until crisp.',
      'Mix onion, tomato, coriander, chili powder, and lemon juice.',
      'Top each papad with masala and serve.',
    ],
    timeMinutes: 10,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 4,
    image: '/images/masalapapad.jpeg',
    
    nutritionPerServing: { calories: 80, protein: 2, carbs: 10, fat: 3 },
  },
  {
    id: 'chicken-tikka-masala',
    title: 'Chicken Tikka Masala',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'chicken', quantity: '500g, cubes' },
      { name: 'yogurt', quantity: '1/2 cup' },
      { name: 'onion', quantity: '1 large, chopped' },
      { name: 'tomato puree', quantity: '1 cup' },
      { name: 'cream', quantity: '1/4 cup' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'oil', quantity: '2 tbsp' },
    ],
    steps: [
      'Marinate chicken in yogurt and spices.',
      'Cook onions and tomato puree to make gravy.',
      'Add chicken and simmer, finish with cream and garam masala.',
    ],
    timeMinutes: 50,
    difficulty: 'medium',
    dietTags: ['non-veg', 'gluten-free'],
    servings: 4,
    image: '/images/chickentikka.jpeg',
    
    nutritionPerServing: { calories: 400, protein: 35, carbs: 10, fat: 25 },
  },
  {
    id: 'shahi-paneer',
    title: 'Shahi Paneer',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'paneer', quantity: '200g, cubes' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato puree', quantity: '1 cup' },
      { name: 'cashew paste', quantity: '2 tbsp' },
      { name: 'cream', quantity: '2 tbsp' },
      { name: 'ghee', quantity: '2 tbsp' },
      { name: 'garam masala', quantity: '1 tsp' },
    ],
    steps: [
      'Sauté onions in ghee, add tomato puree and cashew paste.',
      'Add paneer cubes and cook 5-7 minutes.',
      'Finish with cream and garam masala.',
    ],
    timeMinutes: 35,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
    image: '/images/shaipaneer.jpeg',
    
    nutritionPerServing: { calories: 350, protein: 15, carbs: 20, fat: 22 },
  },


   {
    id: 'dal-bahji',
    title: 'Dal Baati',
    cuisine: 'Rajasthani',
    ingredients: [
      { name: 'wheat flour', quantity: '2 cups' },
      { name: 'ghee', quantity: '4 tbsp' },
      { name: 'toor dal', quantity: '1 cup' },
      { name: 'turmeric', quantity: '1/2 tsp' },
      { name: 'red chili powder', quantity: '1 tsp' },
      { name: 'cumin', quantity: '1 tsp' },
      { name: 'salt', quantity: 'to taste' },
    ],
    steps: [
      'Prepare baati dough, shape into balls and bake or roast.',
      'Cook toor dal with turmeric, chili, and salt.',
      'Serve baati with ghee and dal.',
    ],
    timeMinutes: 60,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 4,
    image: '/images/dalbhaji.jpeg',
    
    nutritionPerServing: { calories: 400, protein: 12, carbs: 50, fat: 18 },
  },
  {
    id: 'bhature',
    title: 'Bhature',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'all-purpose flour', quantity: '2 cups' },
      { name: 'yogurt', quantity: '1/2 cup' },
      { name: 'baking powder', quantity: '1 tsp' },
      { name: 'sugar', quantity: '1 tsp' },
      { name: 'oil', quantity: 'for frying' },
      { name: 'salt', quantity: 'to taste' },
    ],
    steps: [
      'Make soft dough with flour, yogurt, sugar, baking powder, and salt.',
      'Roll into discs and deep fry until golden brown.',
    ],
    timeMinutes: 25,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan'],
    servings: 4,
    image: '/images/aloopuri.jpeg',
    
    nutritionPerServing: { calories: 300, protein: 6, carbs: 40, fat: 12 },
  },
  {
    id: 'kadhi-chawal',
    title: 'Kadhi Chawal',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'besan (gram flour)', quantity: '1/2 cup' },
      { name: 'yogurt', quantity: '1 cup' },
      { name: 'turmeric', quantity: '1/2 tsp' },
      { name: 'chili powder', quantity: '1/2 tsp' },
      { name: 'rice', quantity: '1 cup' },
      { name: 'oil', quantity: '2 tbsp' },
      { name: 'mustard seeds', quantity: '1 tsp' },
    ],
    steps: [
      'Mix besan and yogurt to make kadhi batter.',
      'Cook with turmeric, chili, and tempering.',
      'Serve hot with steamed rice.',
    ],
    timeMinutes: 35,
    difficulty: 'hard',
    dietTags: ['veg', 'gluten-free', 'vegan'],
    servings: 4,
    image: '/images/kadichawal.jpeg',
    
    nutritionPerServing: { calories: 300, protein: 10, carbs: 55, fat: 8 },
  },
  {
    id: 'malai-kofta',
    title: 'Malai Kofta',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'paneer', quantity: '150g, grated' },
      { name: 'potato', quantity: '1 medium, boiled and mashed' },
      { name: 'cashew paste', quantity: '2 tbsp' },
      { name: 'cream', quantity: '2 tbsp' },
      { name: 'tomato puree', quantity: '1 cup' },
      { name: 'oil', quantity: 'for frying' },
      { name: 'garam masala', quantity: '1 tsp' },
    ],
    steps: [
      'Mix paneer, potato, and spices to make kofta balls and fry.',
      'Prepare tomato-cashew gravy.',
      'Add kofta to gravy and simmer with cream.',
    ],
    timeMinutes: 45,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
    image: '/images/malaikofta.jpeg',
    
    nutritionPerServing: { calories: 350, protein: 12, carbs: 25, fat: 22 },
  },
  {
    id: 'chicken-biryani',
    title: 'Chicken Biryani',
    cuisine: 'Indian',
    ingredients: [
      { name: 'basmati rice', quantity: '2 cups' },
      { name: 'chicken', quantity: '500g' },
      { name: 'onion', quantity: '1 large, sliced' },
      { name: 'yogurt', quantity: '1/2 cup' },
      { name: 'biryani masala', quantity: '2 tsp' },
      { name: 'ghee', quantity: '2 tbsp' },
      { name: 'mint', quantity: '2 tbsp, chopped' },
    ],
    steps: [
      'Marinate chicken with yogurt and biryani masala.',
      'Partially cook rice.',
      'Layer rice and chicken, cook on dum until done.',
    ],
    timeMinutes: 60,
    difficulty: 'hard',
    dietTags: ['non-veg', 'gluten-free'],
    servings: 4,
    image: '/images/chickenbriyani.jpeg',
    
    nutritionPerServing: { calories: 450, protein: 35, carbs: 55, fat: 18 },
  },
  {
    id: 'gajar-ka-halwa',
    title: 'Gajar Ka Halwa',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'carrot', quantity: '500g, grated' },
      { name: 'milk', quantity: '1 cup' },
      { name: 'sugar', quantity: '1/2 cup' },
      { name: 'ghee', quantity: '2 tbsp' },
      { name: 'cardamom', quantity: '1/4 tsp' },
      { name: 'cashews', quantity: '2 tbsp, chopped' },
    ],
    steps: [
      'Cook grated carrot in milk until soft.',
      'Add sugar, ghee, and cardamom. Simmer until dry.',
      'Garnish with cashews and serve.',
    ],
    timeMinutes: 50,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 4,
    image: '/images/gajarkahalwa.jpeg',
    nutritionPerServing: { calories: 220, protein: 4, carbs: 30, fat: 10 },
  },
  {
    id: 'aloo-puri',
    title: 'Aloo Puri',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'potato', quantity: '2 medium, boiled and mashed' },
      { name: 'wheat flour', quantity: '2 cups' },
      { name: 'oil', quantity: 'for frying' },
      { name: 'spices', quantity: 'as needed' },
      { name: 'salt', quantity: 'to taste' },
    ],
    steps: [
      'Make puri dough and roll into discs.',
      'Fry until golden brown.',
      'Prepare spiced potato curry and serve with puris.',
    ],
    timeMinutes: 30,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan'],
    servings: 4,
    image: '/images/purialoo.jpeg',
    
    nutritionPerServing: { calories: 350, protein: 6, carbs: 50, fat: 15 },
  },
  {
    id: 'mutton-curry',
    title: 'Mutton Curry',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'mutton', quantity: '500g' },
      { name: 'onion', quantity: '1 large, chopped' },
      { name: 'tomato puree', quantity: '1 cup' },
      { name: 'yogurt', quantity: '1/2 cup' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'oil', quantity: '2 tbsp' },
      { name: 'ginger garlic paste', quantity: '1 tbsp' },
    ],
    steps: [
      'Sauté onion and ginger-garlic paste.',
      'Add mutton and brown.',
      'Add tomato puree, yogurt, and spices. Cook until tender.',
    ],
    timeMinutes: 80,
    difficulty: 'medium',
    dietTags: ['non-veg', 'gluten-free'],
    servings: 4,
    image: '/images/muttoncurry.jpeg',
    
    nutritionPerServing: { calories: 450, protein: 40, carbs: 8, fat: 25 },
  },
  {
    id: 'prawn-fry',
    title: 'Kerala Prawn Fry',
    cuisine: 'South Indian',
    ingredients: [
      { name: 'prawns', quantity: '500g' },
      { name: 'red chili powder', quantity: '1 tsp' },
      { name: 'turmeric', quantity: '1/2 tsp' },
      { name: 'curry leaves', quantity: '10' },
      { name: 'mustard seeds', quantity: '1 tsp' },
      { name: 'oil', quantity: '3 tbsp' },
    ],
    steps: [
      'Marinate prawns with chili, turmeric, and salt.',
      'Fry in oil with mustard seeds and curry leaves until cooked.',
    ],
    timeMinutes: 25,
    difficulty: 'medium',
    dietTags: ['non-veg', 'gluten-free'],
    servings: 4,
    image: '/images/prawnfry.jpeg',
    
    nutritionPerServing: { calories: 300, protein: 30, carbs: 2, fat: 18 },
  },
  {
    id: 'rasgulla',
    title: 'Rasgulla',
    cuisine: 'Bengali',
    ingredients: [
      { name: 'chhena', quantity: '250g' },
      { name: 'sugar', quantity: '2 cups' },
      { name: 'water', quantity: '4 cups' },
      { name: 'cardamom', quantity: '2-3 pods' },
    ],
    steps: [
      'Knead chhena into smooth balls.',
      'Boil in sugar syrup with cardamom until spongy.',
      'Cool and serve chilled.',
    ],
    timeMinutes: 40,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 4,
    image: '/images/rasugulla.jpeg',
    
    nutritionPerServing: { calories: 180, protein: 6, carbs: 35, fat: 2 },
  }
]
