import type { Recipe } from './types'

export const RECIPES: Recipe[] = [
  {
    id: 'chana-masala',
    title: 'Chana Masala',
    cuisine: 'Indian',
    ingredients: [
      { name: 'chickpeas', quantity: '2 cups cooked' },
      { name: 'onion', quantity: '1 medium, chopped' },
      { name: 'tomato', quantity: '2 medium, chopped' },
      { name: 'ginger garlic paste', quantity: '1 tbsp' },
      { name: 'garam masala', quantity: '1 tsp' },
      { name: 'cumin', quantity: '1 tsp' },
      { name: 'turmeric', quantity: '1/2 tsp' },
    ],
    steps: [
      'Sauté onion, add ginger-garlic and spices.',
      'Add tomatoes and cook down.',
      'Add chickpeas and simmer 10 min.',
    ],
    timeMinutes: 35,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan', 'gluten-free'],
    servings: 3,
    nutritionPerServing: { calories: 280, protein: 12, carbs: 42, fat: 6 },
  },
  {
    id: 'paneer-butter-masala',
    title: 'Paneer Butter Masala',
    cuisine: 'Indian',
    ingredients: [
      { name: 'paneer', quantity: '250 g, cubes' },
      { name: 'butter', quantity: '2 tbsp' },
      { name: 'onion', quantity: '1, chopped' },
      { name: 'tomato puree', quantity: '1 cup' },
      { name: 'cream', quantity: '1/4 cup' },
      { name: 'garam masala', quantity: '1 tsp' },
    ],
    steps: [
      'Sauté onion in butter, add tomato puree and spices.',
      'Simmer and add paneer & cream.',
    ],
    timeMinutes: 30,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
    nutritionPerServing: { calories: 420, protein: 18, carbs: 18, fat: 30 },
  },
  {
    id: 'veg-pulao',
    title: 'Veg Pulao',
    cuisine: 'Indian',
    ingredients: [
      { name: 'basmati rice', quantity: '1 cup' },
      { name: 'peas', quantity: '1/2 cup' },
      { name: 'carrot', quantity: '1, diced' },
      { name: 'onion', quantity: '1, sliced' },
      { name: 'cumin', quantity: '1 tsp' },
    ],
    steps: ['Sauté spices & veg.', 'Add rice & water. Cook until done.'],
    timeMinutes: 25,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan', 'gluten-free'],
    servings: 2,
    nutritionPerServing: { calories: 320, protein: 7, carbs: 65, fat: 4 },
  },
  {
    id: 'dal-tadka',
    title: 'Dal Tadka',
    cuisine: 'Indian',
    ingredients: [
      { name: 'toor dal', quantity: '1 cup' },
      { name: 'ghee', quantity: '1 tbsp' },
      { name: 'garlic', quantity: '3 cloves' },
      { name: 'cumin', quantity: '1 tsp' },
      { name: 'turmeric', quantity: '1/2 tsp' },
    ],
    steps: ['Cook dal with turmeric.', 'Temper ghee with cumin & garlic; pour.'],
    timeMinutes: 35,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
    nutritionPerServing: { calories: 260, protein: 12, carbs: 36, fat: 6 },
  },
  {
    id: 'masala-omelette',
    title: 'Masala Omelette',
    cuisine: 'Indian',
    ingredients: [
      { name: 'egg', quantity: '2' },
      { name: 'onion', quantity: '1/4, chopped' },
      { name: 'tomato', quantity: '1/4, chopped' },
      { name: 'green chilli', quantity: '1, chopped' },
    ],
    steps: ['Beat eggs with veg; cook in pan.'],
    timeMinutes: 10,
    difficulty: 'easy',
    dietTags: ['gluten-free', 'none'],
    servings: 1,
    nutritionPerServing: { calories: 220, protein: 14, carbs: 3, fat: 16 },
  },
  {
    id: 'grilled-chicken',
    title: 'Grilled Chicken',
    cuisine: 'Global',
    ingredients: [
      { name: 'chicken breast', quantity: '2 pieces' },
      { name: 'olive oil', quantity: '1 tbsp' },
      { name: 'garlic', quantity: '2 cloves' },
      { name: 'lemon', quantity: '1/2' },
    ],
    steps: ['Marinate and grill 6–7 min/side.'],
    timeMinutes: 20,
    difficulty: 'easy',
    dietTags: ['gluten-free', 'none'],
    servings: 2,
    nutritionPerServing: { calories: 260, protein: 32, carbs: 1, fat: 12 },
  },
  {
    id: 'pasta-arrabbiata',
    title: 'Pasta Arrabbiata',
    cuisine: 'Italian',
    ingredients: [
      { name: 'penne', quantity: '200 g' },
      { name: 'tomato', quantity: '3, crushed' },
      { name: 'garlic', quantity: '3 cloves' },
      { name: 'chilli flakes', quantity: '1 tsp' },
    ],
    steps: ['Boil pasta. Make spicy tomato sauce. Combine.'],
    timeMinutes: 25,
    difficulty: 'easy',
    dietTags: ['veg'],
    servings: 2,
    nutritionPerServing: { calories: 420, protein: 12, carbs: 78, fat: 6 },
  },
  {
    id: 'veg-salad',
    title: 'Chickpea Veg Salad',
    cuisine: 'Global',
    ingredients: [
      { name: 'chickpeas', quantity: '1 cup cooked' },
      { name: 'cucumber', quantity: '1/2, chopped' },
      { name: 'tomato', quantity: '1, chopped' },
      { name: 'olive oil', quantity: '1 tbsp' },
      { name: 'lemon', quantity: '1/2' },
    ],
    steps: ['Toss all with dressing.'],
    timeMinutes: 10,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan', 'gluten-free'],
    servings: 2,
    nutritionPerServing: { calories: 280, protein: 10, carbs: 34, fat: 10 },
  },
  {
    id: 'palak-paneer',
    title: 'Palak Paneer',
    cuisine: 'Indian',
    ingredients: [
      { name: 'spinach', quantity: '300 g' },
      { name: 'paneer', quantity: '200 g' },
      { name: 'onion', quantity: '1, chopped' },
      { name: 'garlic', quantity: '3 cloves' },
    ],
    steps: ['Blanch spinach & blend.', 'Sauté aromatics; add paneer & spinach.'],
    timeMinutes: 30,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 3,
    nutritionPerServing: { calories: 330, protein: 19, carbs: 12, fat: 22 },
  },
  {
    id: 'veg-sandwich',
    title: 'Veg Grilled Sandwich',
    cuisine: 'Global',
    ingredients: [
      { name: 'bread', quantity: '4 slices' },
      { name: 'potato', quantity: '1, boiled & sliced' },
      { name: 'tomato', quantity: '1, sliced' },
      { name: 'onion', quantity: '1/2, sliced' },
    ],
    steps: ['Layer veg, grill 3–4 min.'],
    timeMinutes: 10,
    difficulty: 'easy',
    dietTags: ['veg'],
    servings: 2,
    nutritionPerServing: { calories: 320, protein: 9, carbs: 52, fat: 7 },
  },
  {
    id: 'lentil-soup',
    title: 'Lentil Soup',
    cuisine: 'Global',
    ingredients: [
      { name: 'red lentils', quantity: '1 cup' },
      { name: 'carrot', quantity: '1, diced' },
      { name: 'onion', quantity: '1/2, diced' },
      { name: 'celery', quantity: '1 stalk, diced' },
    ],
    steps: ['Simmer all until tender; season.'],
    timeMinutes: 30,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan', 'gluten-free'],
    servings: 3,
    nutritionPerServing: { calories: 240, protein: 13, carbs: 38, fat: 2 },
  },
  {
    id: 'shakshuka',
    title: 'Shakshuka',
    cuisine: 'Middle Eastern',
    ingredients: [
      { name: 'egg', quantity: '3' },
      { name: 'tomato', quantity: '3, chopped' },
      { name: 'onion', quantity: '1/2, chopped' },
      { name: 'bell pepper', quantity: '1/2, sliced' },
    ],
    steps: ['Simmer sauce; poach eggs in it.'],
    timeMinutes: 25,
    difficulty: 'easy',
    dietTags: ['gluten-free', 'none'],
    servings: 2,
    nutritionPerServing: { calories: 300, protein: 15, carbs: 18, fat: 18 },
  },
  {
    id: 'poha',
    title: 'Kanda Poha',
    cuisine: 'Indian',
    ingredients: [
      { name: 'poha (flattened rice)', quantity: '2 cups' },
      { name: 'onion', quantity: '1, chopped' },
      { name: 'peanuts', quantity: '2 tbsp' },
      { name: 'mustard seeds', quantity: '1/2 tsp' },
    ],
    steps: ['Temper, sauté, add soaked poha; mix.'],
    timeMinutes: 15,
    difficulty: 'easy',
    dietTags: ['veg', 'gluten-free'],
    servings: 2,
    nutritionPerServing: { calories: 290, protein: 7, carbs: 46, fat: 8 },
  },
  {
    id: 'idli-sambar',
    title: 'Idli with Sambar',
    cuisine: 'South Indian',
    ingredients: [
      { name: 'idli batter', quantity: '8 idlis' },
      { name: 'toor dal', quantity: '1/2 cup' },
      { name: 'tamarind', quantity: '1 tbsp pulp' },
      { name: 'sambar powder', quantity: '1 tbsp' },
    ],
    steps: ['Steam idlis; cook sambar; serve hot.'],
    timeMinutes: 40,
    difficulty: 'medium',
    dietTags: ['veg', 'gluten-free'],
    servings: 4,
    nutritionPerServing: { calories: 260, protein: 9, carbs: 50, fat: 3 },
  },
  {
    id: 'aloo-paratha',
    title: 'Aloo Paratha',
    cuisine: 'North Indian',
    ingredients: [
      { name: 'wheat flour', quantity: '2 cups' },
      { name: 'potato', quantity: '2, mashed' },
      { name: 'butter', quantity: '1 tbsp' },
    ],
    steps: ['Stuff, roll, and roast with butter.'],
    timeMinutes: 35,
    difficulty: 'medium',
    dietTags: ['veg'],
    servings: 3,
    nutritionPerServing: { calories: 380, protein: 9, carbs: 62, fat: 10 },
  },
  {
    id: 'veg-fried-rice',
    title: 'Veg Fried Rice',
    cuisine: 'Indo-Chinese',
    ingredients: [
      { name: 'rice', quantity: '2 cups cooked' },
      { name: 'carrot', quantity: '1/2, diced' },
      { name: 'peas', quantity: '1/2 cup' },
      { name: 'soy sauce', quantity: '1 tbsp' },
    ],
    steps: ['Stir-fry veg; add rice & sauce.'],
    timeMinutes: 20,
    difficulty: 'easy',
    dietTags: ['veg'],
    servings: 2,
    nutritionPerServing: { calories: 360, protein: 8, carbs: 64, fat: 8 },
  },
  {
    id: 'tomato-soup',
    title: 'Tomato Soup',
    cuisine: 'Global',
    ingredients: [
      { name: 'tomato', quantity: '5, chopped' },
      { name: 'onion', quantity: '1/2, chopped' },
      { name: 'cream', quantity: '2 tbsp (optional)' },
    ],
    steps: ['Simmer, blend, season.'],
    timeMinutes: 25,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan'],
    servings: 3,
    nutritionPerServing: { calories: 150, protein: 4, carbs: 22, fat: 4 },
  },
  {
    id: 'fish-curry',
    title: 'Simple Fish Curry',
    cuisine: 'Indian',
    ingredients: [
      { name: 'fish', quantity: '300 g' },
      { name: 'coconut milk', quantity: '1 cup' },
      { name: 'onion', quantity: '1, sliced' },
      { name: 'curry leaves', quantity: '6' },
    ],
    steps: ['Sauté onion & spices, add fish and coconut milk; simmer.'],
    timeMinutes: 30,
    difficulty: 'medium',
    dietTags: ['gluten-free', 'none'],
    servings: 3,
    nutritionPerServing: { calories: 320, protein: 24, carbs: 6, fat: 22 },
  },
  {
    id: 'tofu-stirfry',
    title: 'Tofu Veg Stir-fry',
    cuisine: 'Asian',
    ingredients: [
      { name: 'tofu', quantity: '250 g' },
      { name: 'broccoli', quantity: '1 cup florets' },
      { name: 'bell pepper', quantity: '1/2, sliced' },
      { name: 'soy sauce', quantity: '1 tbsp' },
    ],
    steps: ['Stir-fry veg & tofu; add sauce.'],
    timeMinutes: 18,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan'],
    servings: 2,
    nutritionPerServing: { calories: 280, protein: 20, carbs: 14, fat: 16 },
  },
  {
    id: 'oats-porridge',
    title: 'Oats Porridge',
    cuisine: 'Global',
    ingredients: [
      { name: 'rolled oats', quantity: '1/2 cup' },
      { name: 'milk', quantity: '1 cup' },
      { name: 'banana', quantity: '1/2, sliced' },
    ],
    steps: ['Cook oats in milk; top banana.'],
    timeMinutes: 8,
    difficulty: 'easy',
    dietTags: ['veg'],
    servings: 1,
    nutritionPerServing: { calories: 280, protein: 9, carbs: 45, fat: 6 },
  },
  {
    id: 'sprouts-salad',
    title: 'Sprouts Salad',
    cuisine: 'Indian',
    ingredients: [
      { name: 'moong sprouts', quantity: '1 cup' },
      { name: 'onion', quantity: '1/4, chopped' },
      { name: 'tomato', quantity: '1/2, chopped' },
      { name: 'lemon', quantity: '1/2' },
    ],
    steps: ['Toss with spices & lemon.'],
    timeMinutes: 10,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan', 'gluten-free'],
    servings: 2,
    nutritionPerServing: { calories: 160, protein: 10, carbs: 24, fat: 2 },
  },
  {
    id: 'mushroom-matar',
    title: 'Mushroom Matar',
    cuisine: 'Indian',
    ingredients: [
      { name: 'mushroom', quantity: '200 g' },
      { name: 'peas', quantity: '1/2 cup' },
      { name: 'onion', quantity: '1, chopped' },
      { name: 'tomato', quantity: '1, chopped' },
    ],
    steps: [
      'Sauté onion, add tomato & spices; add mushroom & peas and cook.',
    ],
    timeMinutes: 25,
    difficulty: 'easy',
    dietTags: ['veg', 'vegan', 'gluten-free'],
    servings: 3,
    nutritionPerServing: { calories: 210, protein: 9, carbs: 20, fat: 10 },
  },
]
